name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - "yellowdb/**/*.py"
      - "tests/**/*.py"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - master
      - develop
    paths:
      - "yellowdb/**/*.py"
      - "tests/**/*.py"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"

jobs:
  lint:
    name: Ruff Lint, Format & Import Sorting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Ruff
        run: pip install "ruff>=0.6.0"

      - name: Check code formatting
        run: ruff format --check yellowdb/

      - name: Run Ruff linter (including import sorting)
        run: ruff check yellowdb/

  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "build>=1.0.0" "wheel>=0.42.0" "setuptools>=68.0.0"

      - name: Build distribution (wheel and source)
        run: python -m build

      - name: Check distribution contents
        run: |
          pip install twine
          twine check dist/*

      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 7

  test-package:
    name: Test Package Installation
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Install and verify package (wheel + source)
        run: |
          python -m pip install --upgrade pip
          # Test wheel
          pip install dist/yellowdb-*.whl
          python -c "import yellowdb; print(f'✓ YellowDB {yellowdb.__version__} installed successfully')"
          python -c "from yellowdb import YellowDB, Batch, Config; print('✓ All main exports available')"
          # Test source tar.gz
          pip install dist/yellowdb-*.tar.gz
